name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  GOFLAGS: "-buildvcs=false"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.24'
        cache: true
        
    - name: CI Environment Setup
      run: ./scripts/ci_setup.sh
        
    - name: Update dependencies
      run: go mod tidy
      
    - name: Lint
      run: ./scripts/lint.sh
      
    - name: Security Check
      run: ./scripts/security_check.sh
        
    - name: Build
      run: go build -v ./...

    - name: Test
      run: cd test && make test 